baseURL = "//csgsg.org/"
languageCode = "en-us"
title = "UVa CSGSG"
theme = "hugo-initio"
publishDir = "public"


[params]
    name = "CSGSG"
    description = "Computer Science Department Graduate Student Group"
    description2 = "at the University of Virginia"
    address = "85 Engineer's Way, Charlottesville, VA 22904"
    year = 2018
    background = ""
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"

    showSubheader = false
    showUpcoming = true
    showRecentWorks = false
    showDownload = false
    showClients = true

    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    google_analytics_trackerID = "UA-113000385-1"


[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Tea Time"
    url = "/teatime"
    weight = 2
[[menu.main]]
    name = "Lounge"
    url = "/lounge"
    weight = 3
[[menu.main]]
    name = "Students"
    url = "/students"
    weight = 4
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 6
